### ISSUE TITLE
Concerns Regarding `q_posterior_logits`

### ISSUE THREAD

**Issue by qixuema** [cloneofsimo/d3pm#3]
Hi Simo,

Thank you very much for your work. I have a question about one part: why is it `t-2` [here](https://github.com/cloneofsimo/d3pm/blob/3ceb63725ee22b4a37ea437e057021ec2abe1bdb/d3pm_runner.py#L225)?

```python
qmats2 = self.q_mats[t - 2].to(dtype=softmaxed.dtype)
```

**Comment by qixuema** [comment]
Ah, I see. Since the range of values for 't' is [1,1000], we should subtract 1 to convert it to an index (idx). Additionally, since we need to access the q_mat of the previous timestep, we must subtract another 1. Therefore, the total reduction is 2. I hope I've understood it correctly.

**Comment by cloneofsimo** [comment]
aayyy yeah you got it right!
